[package]
name = "tiermaker-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.28.1"
fakeit = "1.3.0"
itertools = "0.13.0"
ratatui = { version = "0.29.0", features = ["all-widgets"] }
unicode-width = "0.2.0"
